# Use an official Node.js runtime as a parent image
FROM node:21

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install --include=dev

COPY . .

RUN npm run build:libs && npm run build:server

CMD ["node", "server/dist/src/index.js"]
